import{S as m,i}from"./assets/vendor-5b791d57.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&r(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const g=async o=>{console.log(`pixabay:search=>[${o}]`);const s="https://pixabay.com/api/",r={key:"42700764-e859e8fc9280be2dbaa9956c4",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0},e=new URLSearchParams(r).toString();console.log("queryParams:",r);const t=`${s}?${e}`,l={method:"GET"};try{return await(await fetch(t,l)).json()}catch(n){throw console.error("p:Error fetching images:",n),n}finally{console.log("pixabay:search.end;")}};console.log("pixaBay.api:loaded...");console.log("renderData:v.2.03");const c=o=>{const s=document.getElementById("gallery");if(s.innerHTML="",o.length===0)return;let a=o.map(r=>`
            <li class="gallery-item">
                <a class="gallery-link" href="${r.largeImageURL}">
                    <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}" />
                </a>
                <ul class="item-info">
                    <li><h3 class="item-title">Likes</h3>    <p class="item-text">${r.likes}</p>
                    <li><h3 class="item-title">Views</h3>    <p class="item-text">${r.views}</p>
                    <li><h3 class="item-title">Comments</h3> <p class="item-text">${r.comments}</p>
                    <li><h3 class="item-title">Downloads</h3><p class="item-text">${r.downloads}</p>
                </ul>
            </li>
        `).join("");s.innerHTML=`<ul class="gallery">${a}</ul>`,new m(".gallery a",{captionsData:"alt",captionDelay:250})};console.log("renderData:loaded...");{const o=document.getElementById("searchForm"),s=document.getElementById("searchInput");o.addEventListener("submit",async a=>{a.preventDefault();const r=s.value.trim();if(r===""){let e="Please enter a search term.";i.error({title:"Error:",message:e,position:"topRight"});return}try{let e=await g(r);console.log("m:data",e);const t=e.hits;if(console.log("m:hits:",t),t.length===0){c(t),i.error({message:`main: Sorry, there are no images matching your search query: [${r}]. Please try again!`});return}c(t)}catch(e){console.error("Error fetching images:",e),i.error({title:"Error:",message:"An error occurred while fetching images. Please try again later."})}})}
//# sourceMappingURL=commonHelpers.js.map
