import{S as c,i}from"./assets/vendor-5b791d57.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&t(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function t(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const m=async o=>{console.log(`pixabay:search=>[${o}]`);const s="https://pixabay.com/api/",t={key:"42700764-e859e8fc9280be2dbaa9956c4",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0},e=new URLSearchParams(t).toString();console.log("queryParams:",t);const r=`${s}?${e}`,n={method:"GET"};try{return await(await fetch(r,n)).json()}catch(l){throw console.error("p:Error fetching images:",l),l}finally{console.log("pixabay:search.end;")}};console.log("pixaBay.api:loaded...");const g=o=>{const s=document.getElementById("gallery");s.innerHTML="",o.forEach(t=>{const e=document.createElement("img");e.src=t.previewURL,e.alt=t.tags,s.appendChild(e)});let a=o.map(t=>`
            <li class="gallery-item">
                <a class="gallery-link" href="${t.largeImageURL}">
                    <img class="gallery-image" src="${t.webformatURL}" alt="${t.tags}" />
                </a>
                <ul class="item-info">
                    <li><h3 class="item-title">Likes</h3>    <p class="item-text">${t.likes}</p>
                    <li><h3 class="item-title">Views</h3>    <p class="item-text">${t.views}</p>
                    <li><h3 class="item-title">Comments</h3> <p class="item-text">${t.comments}</p>
                    <li><h3 class="item-title">Downloads</h3><p class="item-text">${t.downloads}</p>
                </ul>
            </li>
        `).join("");s.innerHTML=`<ul class="gallery">${a}</ul>`,new c(".gallery a",{captionDelay:250,captionsData:"alt"})};console.log("renderData:loaded...");{const o=document.getElementById("searchForm"),s=document.getElementById("searchInput");o.addEventListener("submit",async a=>{a.preventDefault();const t=s.value.trim();if(t===""){let e="Please enter a search term.";i.error({message:e,position:"topRight"});return}try{let e=await m(t);console.log("m:data",e);const r=e.hits;if(console.log("m:hits:",r),r.length===0){i.warning({title:"Warning",message:`main:Sorry, there are no images matching your search query: [${t}]. Please try again!`});return}g(r)}catch(e){console.error("Error fetching images:",e),i.error({title:"Error",message:"An error occurred while fetching images. Please try again later."})}})}
//# sourceMappingURL=commonHelpers.js.map
